- hosts: kube-master
  vars_files:
    - ../defaults/main.yml

  tasks:
    - name: 注册变量 LB_IF_TMP
      shell: "ip a|grep '{{ inventory_hostname }}/'|awk '{print $NF}'"
      register: LB_IF_TMP

    - name: 设置变量 LB_IF
      set_fact: LB_IF={{ LB_IF_TMP.stdout }}

    - name: 创建相关目录
      file: name={{ item }} state=directory
      with_items:
      - /etc/haproxy
      - /etc/keepalived 

    - name: 配置 haproxy
      template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

    - name: 配置 keepalived 主节点
      template: src=keepalived-master.conf.j2 dest=/etc/keepalived/keepalived.conf
      when: LB_ROLE == "master"

    - name: 配置 keepalived 备节点
      template: src=keepalived-backup.conf.j2 dest=/etc/keepalived/keepalived.conf
      when: LB_ROLE == "backup"

    - name: 安装 haproxy+keepalived
      package: name={{ item }} state=present
      with_items:
      - haproxy
      - keepalived
      ignore_errors: true

    - name: 开机启用haproxy服务
      shell: systemctl enable haproxy
      ignore_errors: true 

    - name: 重启haproxy服务
      shell: systemctl restart haproxy
      tags: restart_lb

    - name: 开机启用keepalived服务
      shell: systemctl enable keepalived
      ignore_errors: true

    - name: 重启keepalived服务
      shell: systemctl restart keepalived
      tags: restart_lb
